[project]
name = "pypandas"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "sd44",email = "sd44sd44@yeah.net"},
]
dependencies = [
    "pandas>=2.2.3",
    "qtpy>=2.4.3",
    "pyside6>=6.11.1",
    "openpyxl>=3.1.5",
    "xlrd>=2.0.1",
    "et-xmlfile==2.0.0",
    "numpy==2.4.6",
    "openpyxl==3.1.5",
    "packaging==26.2",
    "pandas==3.0.3",
    "pyside6==6.11.1",
    "pyside6-addons==6.11.1",
    "pyside6-essentials==6.11.1",
    "python-dateutil==2.9.0.post0",
    "qtpy==2.4.3",
    "shiboken6==6.11.1",
    "six==1.17.0",
    "tzdata==2026.2; sys_platform == \"emscripten\" or sys_platform == \"win32\"",
    "xlrd==2.0.2",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
pypandas = "app:main"


[tool.pdm]
distribution = false

[tool.pdm.scripts]
pypandas = "python app.py"
