# Configuration file for gbp <command>  gbp.conf
# https://salsa.debian.org/debian/entr/-/blob/debian/latest/debian/gbp.conf

[DEFAULT]

# Manage a "pristine-tar" branch:
pristine-tar = True
pristine-tar-commit = True

# Use Debian-style DEP-14 branch names:
upstream-branch=upstream/latest
debian-branch=debian/latest

# Lax requirement to use branch name 'debian/latest' so that git-buildpackage
# will always build using the currently checked out branch as the Debian branch.
# This makes it easier for contributors to work with feature and bugfix
# branches.
ignore-branch = True


# Build packages with pbuilder:
# pbuilder = True
# Or use sbuild:
builder = sbuild

# Sign tags (optional):
sign-tags = True
keyid = DBBF53F41DF90D31A0C0D0134F4D76C33BA3B42D

# Ease dropping / adding patches
patch-numbers = False

# Ensure a human always reviews all the debian/changelog entries.
spawn-editor = always

# No need to confirm package name or version at any time, git-buildpackage
# always gets it right.
interactive = False

# Ensure we always target Debian on Debian branches
dch-opt = --vendor=debian

# If this package ever needs to be maintained for Ubuntu, remember to override
# the branch, tag and commit messages
#debian-branch = ubuntu/24.04-noble
#debian-tag = ubuntu/%(version)s
#debian-tag-msg = %(pkg)s Ubuntu release %(version)s
#dch-opt = --vendor=ubuntu
